All changes since project started
googleinterns/step219-2020 pull request #30
Opened 2020-08-26 12:20 UTC by Gor1x

2020-08-26 13:16 UTC, joe-fowler requested changes
I've left comments on code. I also have one more comment: you should remove all the `.class` files and any generated files from git. Basically, the files which are generated when you build the project should not be included in the repo. You can remove them with `git rm`, which will not delete real files but will remove them from git, and then you can put the names of those files in the `.gitignore` file to stop them coming back. For example, you might put this in your `.gitignore`:

```
  .*
  !.gitignore
  *.class
  /target
```

This will ignore:

  * Files starting with a dot, except for `.gitignore`, which we want.
  * All `class` files, since they are just build artefacts
  * All files under `/target`, which should be all the generated files if I understand this right.

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +async function loadToDos() {
The function is `async`, but the body doesn't use `await`. You probably want to change:

```javascript
  async function loadToDos() {
    fetch('/send-task').then(response => response.json()).then((tasksList) => {
      // stuff that uses tasksList
    });
  }
```

into this:

```javascript
  async function loadToDos() {
    const response = await fetch('/send-task');
    const tasksList = await response.json();
    // stuff that uses tasksList
  }
```

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +  for (view of event.path)
Please put '{' around the loop body, it makes the code more obvious.

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +  fetch('/send-task').then(response => response.json()).then((tasksList) => {
The name `/send-task` makes it sound like it changes the task, but this code loads the task. If `/send-task` is supposed to handle every task operation, maybe it should just be `/task`?

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +  });
So when you edit something, it removes the task and recreates it from scratch? I thought the server side supported editing tasks directly without deleting them?

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +}
I don't think this function should exist. You can just do the confirm directly.

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +  })
Why does `removeElement` call both `/remove-task` and `/send-task`?

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +async function editFieldData(event) {
Please add comments to this function.

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +async function loadToDos() {
Please add comments to this function

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/script.js
> +async function removeElement(view) {
Please add comments to this function.

2020-08-26 13:16 UTC, joe-fowler commented on src/main/webapp/style.css
> +
The indentation in this file is not consistent. Please make it consistent. Use the same number of spaces for indentation in all of the css entries.

2020-08-26 13:16 UTC, joe-fowler commented on target/portfolio-1/script.js
> +async function loadToDos() {
This is the same as `src/main/webapp/script.js`, right? It's just a copy made by the compiler or tools?

2020-08-26 13:16 UTC, joe-fowler commented on target/portfolio-1/style.css
> +#app-title {
This is the same as `src/main/webapp/style.css`, right? It's just a copy made by the compiler or tools?

2020-08-26 14:13 UTC, automatthias reviewed
Here are my comments to the first few files. I'll continue reviewing tomorrow.

2020-08-26 14:13 UTC, automatthias commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +@WebServlet("/send-task")
In this context it might not be clear what "send" means. The servlet is on the receiving side, so it would be more of "receive-task", but I guess it's best to use words that don't depend on the point of view (sending vs receiving are two views of one transfer operation).

2020-08-26 14:13 UTC, automatthias commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +      Task task = new Task(new Time(date),
I've seen this or a very similar block of code in TaskMainServlet.java. It might be a good idea to deduplicate them.

2020-08-26 14:13 UTC, automatthias commented on src/main/java/com/google/sps/src/Place.java
> +  private String string;
What kind of information will this variable hold? The address?

2020-08-26 14:13 UTC, automatthias commented on src/main/java/com/google/sps/src/Time.java
> +/*
If it's not used, I suggest removing this comment. If you want to hold this code for later use, you can do that in a separate branch.

2020-08-30 06:50 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/DeleteTaskServlet.java
> +  ArrayList<Key> keys;
This file won't be used, it is deleted now.

2020-08-30 06:50 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/DeleteTaskServlet.java
> +    datastore.delete(keys.get(id));
This file will be deleted.

2020-08-30 06:52 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/EditTaskServlet.java
> +    }
This file will be deleted.

2020-08-30 06:53 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/RemoveTaskServlet.java
> +  public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
This file will be deleted

2020-08-30 06:53 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/EditTaskServlet.java
> +  public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
This file will be deleted

2020-08-30 09:21 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskMainServlet.java
> +  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
Done

2020-08-30 09:21 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskMainServlet.java
> +  public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
This file will be deleted

2020-08-30 09:24 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskMainServlet.java
> +  ArrayList<Task> tasks;
This file will be deleted

2020-08-30 09:24 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +  private ArrayList<Task> tasks;
Done

2020-08-30 09:25 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +        tasks.add(task);
Agree. Done

2020-08-30 11:59 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +      String comment = (String)entity.getProperty("comment");
Added try catch blocks. Now server sends BAD_REQUEST if user do something like that

2020-08-30 12:11 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +  public void doPost(HttpServletRequest request, HttpServletResponse response) throws IOException {
Done

2020-08-30 12:15 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +          if (fieldName.equals("task_placeData")) {
task_placeData is the name of html field, so it was easier to send it like that.

Agree with second. Changed it.

2020-08-30 12:31 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +          }
Done.

2020-08-30 12:32 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +  private Task getTask(HttpServletRequest request, long id) {
I renamed it

2020-08-30 12:33 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +      tasks.removeIf(element -> (element.getNumber() == number));
Datastore is changed by other servlet. Think this servlets should be merged.

2020-08-30 12:51 UTC, Gor1x commented on src/main/webapp/style.css
> +
Done

2020-08-30 12:53 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +      Task task = new Task(new Time(date),
TaskMainServlet is deleted now

2020-08-30 12:53 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +@WebServlet("/send-task")
This name is changed

2020-08-30 12:54 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/DeleteTaskServlet.java
> +  public void init() {
This file is deleted

2020-08-30 12:54 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/EditTaskServlet.java
> +@WebServlet("/edit-task")
Name is changed now

2020-08-30 13:11 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/DeleteTaskServlet.java
> +  public void init() {
This file is deleted

2020-08-30 13:11 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/EditTaskServlet.java
> +@WebServlet("/edit-task")
This file is deleted

2020-08-30 13:12 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/EditTaskServlet.java
> +    System.out.println(id);
This file is deleted

2020-08-30 13:12 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/RemoveTaskServlet.java
> +        System.out.println("Key doesn't exists");
This file is deleted

2020-08-30 13:12 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +@WebServlet("/send-task")
The name is changed

2020-08-30 13:13 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +      Task task = new Task(new Time(date),
TaskMainServlet.java is deleted now

2020-08-30 13:13 UTC, Gor1x commented on src/main/java/com/google/sps/src/Time.java
> +/*
Done

2020-08-30 13:14 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +    } else if (type.equals("edit")) {
Maybe I should merge these classes, but I changed their names and now it is more understandable.

2020-08-30 13:14 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/TaskServlet.java
> +    Task task = getTask(request, taskEntity.getKey().getId());
Done

2020-08-30 13:16 UTC, Gor1x commented on src/main/java/com/google/sps/src/Task.java
> +  private long number;
Done

2020-08-30 13:17 UTC, Gor1x commented on src/main/java/com/google/sps/src/Task.java
> +  }
I will do it, but I am not sure if object like that should communicate with datastore

2020-08-30 13:27 UTC, Gor1x commented on src/main/java/com/google/sps/src/Place.java
> +  private String string;
It is a bit fictional. Later it should be remove when we will add positions on map.

2020-08-30 13:28 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/RemoveTaskServlet.java
> +    System.out.println("LOG: doPost /remove-task request");
I have problems with logging library :(

2020-08-30 13:29 UTC, Gor1x commented on src/main/java/com/google/sps/src/Place.java
> +  private String string;
it is renamed now.

2020-08-30 13:32 UTC, Gor1x commented on src/main/java/com/google/sps/src/TaskText.java
> +}
It is done like that because task title and task comment should be together. They are different from place and time.

But I am agree that it is too hard and long, I will change that.

2020-09-03 12:53 UTC, closed without merging