Fixes for pull request
googleinterns/step219-2020 pull request #33
Opened 2020-08-30 16:08 UTC by Gor1x

2020-08-31 17:28 UTC, joe-fowler requested changes

2020-08-31 17:28 UTC, joe-fowler commented on src/main/webapp/script.js
> +  let response = await fetch('/update-local-task-list');
nit: why `let` and not `const`?

2020-08-31 17:28 UTC, joe-fowler commented on src/main/webapp/script.js
> +  for (view of event.path) {
```javascript
  for (const view of event.path)
```

Without `var`, `let`, or `const` in there, you're updating the global variable `window.view` instead of just a local variable :)

2020-08-31 17:28 UTC, joe-fowler commented on src/main/webapp/script.js
> +  await fetch('/update-local-task-list', {
You could do the same thing here as you did above:

```javascript
  const req1 = fetch(...);
  const req2 = fetch(...);
  await req1;
  await req2;
```

2020-08-31 17:28 UTC, joe-fowler commented on src/main/java/com/google/sps/servlets/LocalUpdateServlet.java
> +@WebServlet("/update-local-task-list")
What is this handler for? What makes it different from update-server-task-list? It isn't obvious to me, maybe you could add such things as comments in this file and in the other file.

2020-09-04 18:30 UTC, Gor1x commented on src/main/webapp/script.js
> +  let response = await fetch('/update-local-task-list');
Done

2020-09-04 18:31 UTC, Gor1x commented on src/main/webapp/script.js
> +  for (view of event.path) {
Agree, now I know that!

2020-09-04 18:31 UTC, Gor1x commented on src/main/webapp/script.js
> +  await fetch('/update-local-task-list', {
Done

2020-09-04 18:32 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/LocalUpdateServlet.java
> +@WebServlet("/update-local-task-list")
I think it is more beautiful readable and easy to split changes into datastore and local. It should be discussed

2020-09-08 11:16 UTC, joe-fowler approved these changes

2020-09-08 16:00 UTC, merged