Interface improvements
googleinterns/step219-2020 pull request #35
Opened 2020-09-08 15:55 UTC by Gor1x

Now tasks can be changed with their own view
They can be added by button
They can be chosen.
They can be edited and removed while chosen.

2020-09-08 16:59 UTC, joe-fowler requested changes
I see diffs here which I wasn't expecting. It looks like you are adding the `LocalUpdateServlet` again? Do you need to merge master into this branch?

2020-09-09 10:49 UTC, joe-fowler requested changes

2020-09-09 10:49 UTC, joe-fowler commented on src/main/webapp/script.js
> +  const changeRequestText = "type=change&number=" + id
what if I create a TODO with the title `&place=42`? You should probably make sure this doesn't generate bad values. One option is to use `encodeURIComponent` to turn the values into safely escaped strings. Another option is to use `URLSearchParams`, which handles it all for you:

```javascript
  const params = new URLSearchParams();
  params.set('title', title.value);
  ...
  const changeRequestText = params.toString();
```

2020-09-09 10:49 UTC, joe-fowler commented on src/main/webapp/script.js
> +async function untoggleElement() {
Please add comments in this function to explain what it is doing.

2020-09-09 10:49 UTC, joe-fowler commented on src/main/webapp/script.js
> +  toggleElement(currentElement)
Please add comments to this function. I don't understand why this code does what it does.

2020-09-09 10:49 UTC, joe-fowler commented on src/main/webapp/script.js
>    liElement.setAttribute("id", task.datastoreId);
There are more direct ways of updating the class and id fields:

```javascript
  liElement.classList.add('tasklist_node', 'shadowed_element');
  liElement.id = task.datastoreId;
```

2020-09-09 10:49 UTC, joe-fowler commented on src/main/webapp/script.js
> +  });
You have snippets like this in many places, maybe you could have a helper function?

2020-09-09 10:49 UTC, joe-fowler commented on src/main/webapp/script.js
> +
Don't you need `return btnElement`?

2020-09-09 16:52 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/LocalUpdateServlet.java
> +      return;
because I dont need redirect for this. Should it be changed?

2020-09-09 16:53 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/LocalUpdateServlet.java
> +        if (task.getDatastoreId() == number) {
OK, I'll see if it can be changed easy

2020-09-09 17:05 UTC, joe-fowler commented on src/main/java/com/google/sps/servlets/LocalUpdateServlet.java
> +      return;
I think this comment chain probably should merge with the one below. Basically, do you *ever* need a redirect? Are there any HTML forms left in the app, or is everything javascript?

2020-09-09 17:37 UTC, Gor1x commented on src/main/webapp/script.js
> +  await req1;
Because otherwise if I dont do req1 fetch, the page doesn't work correctly after reloadin, because my cache array is not changed.

2020-09-09 17:37 UTC, Gor1x commented on src/main/webapp/script.js
> +  toggleElement(currentElement)
I have added comments, but I guess I need to find more beautiful word for this. Toggling is not understandable enough

2020-09-09 17:44 UTC, Gor1x commented on src/main/webapp/script.js
> +  });
Now it is done with "fetchHelper" function.

2020-09-09 17:44 UTC, Gor1x commented on src/main/webapp/script.js
> +
No, I don't need id. It is already in my HTML, so I need to give it needed properties

2020-09-09 17:46 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/LocalUpdateServlet.java
>      response.sendRedirect("/index.html");
Right, I thought it is needed, but it is not. I removed that.

2020-09-09 17:49 UTC, Gor1x commented on src/main/java/com/google/sps/servlets/ServerUpdateServlet.java
>      }
Right, I've done that

2020-09-09 17:52 UTC, Gor1x commented on src/main/webapp/script.js
>    liElement.setAttribute("id", task.datastoreId);
I thought that setting attributes are better because there are special functions for that and it can protect me from some damage if something goes wrong. Should I change that in this pull request?

2020-09-10 10:40 UTC, joe-fowler requested changes

2020-09-10 10:40 UTC, joe-fowler commented on src/main/java/com/google/sps/src/DateTime.java
> +
I don't think we need these, they are just derived from `calendarDate`. When you need the time, you can call `getTimeAsString()`, and when you need the date, you can call `getDateAsString()`.

If you have `time` and `date` variables as well, you have to be very careful when updating things or you might accidentally end up with them out of sync. If you only have `calendarDate`, it is impossible to have inconsistent values.

2020-09-11 08:52 UTC, joe-fowler approved these changes

2020-09-11 11:19 UTC, merged